WITH CUSTOMERS AS (

    SELECT * FROM {{ ref('stg_customers') }}

),

ORDERS AS (

    SELECT * FROM {{ ref('stg_orders') }}

),

PAYMENTS AS (

    SELECT * FROM {{ ref('stg_payments') }}

),

CUSTOMER_ORDERS AS (

    SELECT
        ORD.CUSTOMER_ID
        ,MIN(ORD.ORDER_DATE) AS FIRST_ORDER_DATE
        ,MAX(ORD.ORDER_DATE) AS MOST_RECENT_ORDER_DATE
        ,COUNT(ORD.ORDER_ID) AS NUMBER_OF_ORDERS
        ,SUM(PMT.AMOUNT) AS PAYMENT_AMOUNT
    FROM ORDERS ORD
    LEFT JOIN PAYMENTS PMT
        ON ORD.ORDER_ID = PMT.ORDER_ID
        AND PMT.STATUS = 'success'
    GROUP BY ORD.CUSTOMER_ID

),

FINAL AS (

    SELECT
        CUSTOMERS.CUSTOMER_ID,
        CUSTOMERS.FIRST_NAME,
        CUSTOMERS.LAST_NAME,
        CUSTOMER_ORDERS.FIRST_ORDER_DATE,
        CUSTOMER_ORDERS.MOST_RECENT_ORDER_DATE,
        COALESCE(CUSTOMER_ORDERS.NUMBER_OF_ORDERS, 0) AS NUMBER_OF_ORDERS,
        COALESCE(CUSTOMER_ORDERS.PAYMENT_AMOUNT,0) AS LIFETIME_VALUE
    FROM CUSTOMERS
    LEFT JOIN CUSTOMER_ORDERS USING (CUSTOMER_ID)

)

SELECT * FROM FINAL