WITH ORDERS AS (
    SELECT * FROM {{ ref('stg_orders') }}
),

PAYMENTS AS (
    SELECT * FROM {{ ref('stg_payments') }}
),

FINAL AS (
    SELECT
        ORD.ORDER_ID
        ,ORD.CUSTOMER_ID
        ,SUM(PMT.AMOUNT) AS TOTAL_PAYMENT_AMOUNT
        ,SUM(CASE WHEN PMT.STATUS = 'fail' THEN 0 ELSE PMT.AMOUNT END) AS TOTAL_SUCCESS_AMOUNT
        ,SUM(CASE WHEN PMT.STATUS = 'fail' THEN PMT.AMOUNT ELSE 0 END) AS TOTAL_FAIL_AMOUNT
    FROM ORDERS ORD
    LEFT OUTER JOIN PAYMENTS PMT
        ON ORD.ORDER_ID = PMT.ORDER_ID
    GROUP BY 
        ORD.ORDER_ID
        ,ORD.CUSTOMER_ID
)

SELECT * FROM FINAL